Repository Las-Fuerzas-Del-Cielo/Sistema-Anti-Fraude-Electoral, pull requests merged in 2023-10, with the labels that each got.

#76 Implements localstack setup
  api/Makefile
  api/README.md
  api/bin/set_env_vars
  api/bin/setup_localstack.py
  api/docker-compose.yml
  api/examples/README.md
  api/examples/index.js
  api/index.js
  api/package-lock.json
  api/package.json
Labels: backend

#85 fix and improve setup
  api/bin/set_env_vars
  api/docker-compose.yml
  api/package.json
Labels: backend

#86 New screen profile
  frontend/src/components/buttonSignout/index.tsx
  frontend/src/components/dataProfile/index.tsx
  frontend/src/components/dataProfile/styles.css
  frontend/src/components/index.ts
  frontend/src/main.tsx
  frontend/src/pages/profile/index.ts
  frontend/src/pages/profile/profile.tsx
Labels: frontend

#82 Configuración de ESLint y Prettier
  frontend/.eslintrc.cjs
  frontend/package.json
  frontend/tsconfig.json
  frontend/yarn.lock
Labels: frontend

#89 Upload image component
  frontend/src/assets/icon/upload.svg
  frontend/src/components/uploadImage/index.tsx
  frontend/src/utils/utils.ts
Labels: frontend

#102 feat(frontend); add DataSentSuccessful component
  frontend/src/assets/images/back-arrow.svg
  frontend/src/assets/images/check-icon.svg
  frontend/src/assets/images/square-logo.svg
  frontend/src/assets/logos/fenix-white.svg
  frontend/src/components/dataSentSuccessful/index.tsx
  frontend/src/components/dataSentSuccessful/styles.css
  frontend/src/routes/routes.tsx
Labels: SECOND-APPROVAL-NEEDED

#114 Removed default Vite font in index.css
  frontend/src/index.css
Labels: SECOND-APPROVAL-NEEDED

#105 Alineamiento automático de imagenes de comprobantes y telegramas para facilitar el reconocimiento automático de caracteres
  Fuentes_de_datos/alineamiento_de_imagenes/Dockerfile
  Fuentes_de_datos/alineamiento_de_imagenes/LICENSE
  Fuentes_de_datos/alineamiento_de_imagenes/README.md
  Fuentes_de_datos/alineamiento_de_imagenes/align.py
  Fuentes_de_datos/alineamiento_de_imagenes/examples/00001.jpg
  Fuentes_de_datos/alineamiento_de_imagenes/examples/00002.jpg
  Fuentes_de_datos/alineamiento_de_imagenes/examples/00003.jpg
  Fuentes_de_datos/alineamiento_de_imagenes/examples/template1.png
  Fuentes_de_datos/alineamiento_de_imagenes/inference.py
  Fuentes_de_datos/alineamiento_de_imagenes/input/elecciones/README.md
  Fuentes_de_datos/alineamiento_de_imagenes/models.yaml
  Fuentes_de_datos/alineamiento_de_imagenes/models/README.md
  Fuentes_de_datos/alineamiento_de_imagenes/requirements.txt
  Fuentes_de_datos/alineamiento_de_imagenes/src/__init__.py
  Fuentes_de_datos/alineamiento_de_imagenes/src/inv3d_model/__init__.py
  Fuentes_de_datos/alineamiento_de_imagenes/src/inv3d_model/__pycache__/__init__.cpython-310.pyc
  Fuentes_de_datos/alineamiento_de_imagenes/src/inv3d_model/model_zoo.py
  Fuentes_de_datos/alineamiento_de_imagenes/src/inv3d_model/models/__init__.py
  Fuentes_de_datos/alineamiento_de_imagenes/src/inv3d_model/models/__pycache__/__init__.cpython-310.pyc
  Fuentes_de_datos/alineamiento_de_imagenes/src/inv3d_model/models/__pycache__/model_factory.cpython-310.pyc
  Fuentes_de_datos/alineamiento_de_imagenes/src/inv3d_model/models/geotr/__init__.py
  Fuentes_de_datos/alineamiento_de_imagenes/src/inv3d_model/models/geotr/__pycache__/__init__.cpython-310.pyc
  Fuentes_de_datos/alineamiento_de_imagenes/src/inv3d_model/models/geotr/__pycache__/extractor.cpython-310.pyc
  Fuentes_de_datos/alineamiento_de_imagenes/src/inv3d_model/models/geotr/__pycache__/geotr.cpython-310.pyc
  Fuentes_de_datos/alineamiento_de_imagenes/src/inv3d_model/models/geotr/__pycache__/geotr_core.cpython-310.pyc
  Fuentes_de_datos/alineamiento_de_imagenes/src/inv3d_model/models/geotr/__pycache__/geotr_template.cpython-310.pyc
  Fuentes_de_datos/alineamiento_de_imagenes/src/inv3d_model/models/geotr/__pycache__/geotr_template_large.cpython-310.pyc
  Fuentes_de_datos/alineamiento_de_imagenes/src/inv3d_model/models/geotr/__pycache__/position_encoding.cpython-310.pyc
  Fuentes_de_datos/alineamiento_de_imagenes/src/inv3d_model/models/geotr/extractor.py
  Fuentes_de_datos/alineamiento_de_imagenes/src/inv3d_model/models/geotr/geotr.py
  Fuentes_de_datos/alineamiento_de_imagenes/src/inv3d_model/models/geotr/geotr_core.py
  Fuentes_de_datos/alineamiento_de_imagenes/src/inv3d_model/models/geotr/geotr_template.py
  Fuentes_de_datos/alineamiento_de_imagenes/src/inv3d_model/models/geotr/geotr_template_large.py
  Fuentes_de_datos/alineamiento_de_imagenes/src/inv3d_model/models/geotr/position_encoding.py
  Fuentes_de_datos/alineamiento_de_imagenes/src/inv3d_model/models/model_factory.py
  Fuentes_de_datos/alineamiento_de_imagenes/src/inv3d_util/__init__.py
  Fuentes_de_datos/alineamiento_de_imagenes/src/inv3d_util/__pycache__/__init__.cpython-310.pyc
  Fuentes_de_datos/alineamiento_de_imagenes/src/inv3d_util/__pycache__/image.cpython-310.pyc
  Fuentes_de_datos/alineamiento_de_imagenes/src/inv3d_util/__pycache__/load.cpython-310.pyc
  Fuentes_de_datos/alineamiento_de_imagenes/src/inv3d_util/__pycache__/mapping.cpython-310.pyc
  Fuentes_de_datos/alineamiento_de_imagenes/src/inv3d_util/__pycache__/misc.cpython-310.pyc
  Fuentes_de_datos/alineamiento_de_imagenes/src/inv3d_util/__pycache__/path.cpython-310.pyc
  Fuentes_de_datos/alineamiento_de_imagenes/src/inv3d_util/image.py
  Fuentes_de_datos/alineamiento_de_imagenes/src/inv3d_util/load.py
  Fuentes_de_datos/alineamiento_de_imagenes/src/inv3d_util/mapping.py
  Fuentes_de_datos/alineamiento_de_imagenes/src/inv3d_util/mask.py
  Fuentes_de_datos/alineamiento_de_imagenes/src/inv3d_util/misc.py
  Fuentes_de_datos/alineamiento_de_imagenes/src/inv3d_util/parallel.py
  Fuentes_de_datos/alineamiento_de_imagenes/src/inv3d_util/path.py
  Fuentes_de_datos/alineamiento_de_imagenes/src/inv3d_util/visualization.py
Labels: SECOND-APPROVAL-NEEDED

#92 Creacion de la barra de progreso
  frontend/.prettierrc
  frontend/src/assets/check-icono.svg
  frontend/src/components/index.ts
  frontend/src/components/progressIndicator/index.tsx
  frontend/src/components/progressIndicator/styles.css
  frontend/src/components/progressIndicator/types.ts
Labels: frontend

#143 [FRONT] fix login form password eye size
  frontend/src/components/input/index.tsx
Labels: SECOND-APPROVAL-NEEDED

#144 [FRONT] Selector actualizado al figma y filtros de resultados totales mock
  frontend/src/assets/icon/selector-icon.svg
  frontend/src/components/selector/Exports.tsx
  frontend/src/components/selector/Selector.tsx
  frontend/src/pages/results/filter.tsx
  frontend/src/pages/results/index.ts
  frontend/src/routes/routes.tsx
Labels: SECOND-APPROVAL-NEEDED

#156 [FRONT] Update step three - data upload v2
  frontend/src/assets/icon/mail-appealed.svg
  frontend/src/assets/icon/mail-closed.svg
  frontend/src/assets/icon/mail-contested.svg
  frontend/src/assets/icon/mail-invalid.svg
  frontend/src/assets/icon/mail-person.svg
  frontend/src/assets/icon/warn-icon.svg
  frontend/src/components/flatList/index.tsx
  frontend/src/components/flatList/types.ts
  frontend/src/index.css
  frontend/src/pages/load-information/loadInformation.tsx
Labels: SECOND-APPROVAL-NEEDED

#171 [API] Upload acta feature
  api/package.json
  api/src/controllers/upload.ts
  api/src/routes/index.ts
  api/src/routes/upload.ts
  api/src/types/global.d.ts
  api/swagger.json
  api/swagger.yaml
  api/yarn.lock
Labels: MERGE CONFLICTS

#155 Carga de datos de mesa & Header fixes
  frontend/src/assets/images/back-arrow.svg
  frontend/src/assets/images/menu.svg
  frontend/src/assets/logos/fenix-new.svg
  frontend/src/components/formHeader/index.tsx
  frontend/src/pages/desk-data/DeskData.tsx
  frontend/src/routes/routes.tsx
Labels: SECOND-APPROVAL-NEEDED
